### ISSUE TITLE
Trying to run your Cucumber-appium-ruby-example framwork but didnt work.

### ISSUE THREAD

**Issue by lummyare** [haroon-sheikh/example-ruby-cucumber-appium#7]
Hi Haroon,
I user to work for Sky in London Osterley but i have left. I am trying to use your framework but its not working. Please could you help me configure your framework for my ios/android app?

**Comment by lummyare** [comment]
here are the error I encountered:

When I run: bundle exec cucumber -r features -p iphone_simulator
I get the following error:

/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/ast/step.rb:80: warning: circular argument reference - name
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/activesupport-4.0.0/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/activesupport-4.0.0/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/activesupport-4.0.0/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
cannot load such file -- test/unit/assertions (LoadError)
/Users/lummy/cucumber-appium-ruby-example/features/support/env.rb:11:in `require'
/Users/lummy/cucumber-appium-ruby-example/features/support/env.rb:11:in `<top (required)>'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load_code_file'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:183:in `load_step_definitions'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:42:in `run!'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/lummy/.rvm/gems/ruby-2.4.1/gems/cucumber-1.3.8/bin/cucumber:13:in `<top (required)>'
/Users/lummy/.rvm/gems/ruby-2.4.1/bin/cucumber:23:in `load'
/Users/lummy/.rvm/gems/ruby-2.4.1/bin/cucumber:23:in `<main>'
/Users/lummy/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/lummy/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by lummyare** [comment]
Please what am i doing wrong? what do i need to do to fix this? Please i dint mind to pay you £200 to help me configure this framework in order to work for my ios/android app pleasee. my email is lummyare@gmail.com. I use to work for SkyQ app team

**Comment by nahomwosenu** [comment]
I can help you fix this but only for Android.
